export const ARTISTS = [
  {
    id: "sarah-mitchell",
    name: "Marcus Thompson",
    category: "Watercolor & Abstract Art",
    tagline: "Artists living with Autism",
    soldCount: 47,
    shortBio:
      "Emma discovered her passion for watercolor painting at age 12. Through art, she found a way to communicate her inner world and connect with others on a profound level.",
    fullBio:
      "Sarah discovered her passion for watercolor painting at age 12. Living with autism, she finds peace and expression through capturing the delicate beauty of nature. Her unique perspective allows her to see colors and patterns that others often miss. Each brushstroke is deliberate, each color choice meaningful.",
    medium: "Watercolor",
    image: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&q=80",
    coverImage: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=1200&q=80",
  },
  {
    id: "marcus-chen",
    name: "Marcus Thompson",
    category: "Metal Sculpture & Design",
    tagline: "Surreal Artists living with Autism",
    soldCount: 32,
    shortBio:
      "Marcus has been working with metal for over 5 years. His intricate sculptures of butterflies, flowers, and abstract forms showcase incredible attention to detail and patience. Each piece takes days to complete.",
    fullBio:
      "Marcus has been working with metal for over 5 years. His intricate sculptures of butterflies, flowers, and abstract forms showcase incredible attention to detail and patience. Each piece takes days to complete.",
    medium: "Metal Art",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80",
    coverImage: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=1200&q=80",
  },
  {
    id: "emma-rodriguez",
    name: "Daniel Lichben",
    category: "Abstract & Mixed Media",
    tagline: "Artists with Down Syndrome",
    soldCount: 56,
    shortBio:
      "Sofia's bold use of color and texture creates mesmerizing abstract pieces. She loves experimenting with different materials and techniques to push the boundaries of traditional art.",
    fullBio:
      "Emma brings an infectious energy to her mixed media work, layering textures, colors, and found materials to create vibrant celebrations of everyday beauty. Her bold use of color and texture creates mesmerizing abstract pieces.",
    medium: "Mixed Media",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
    coverImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&q=80",
  },
  {
    id: "david-park",
    name: "David Park",
    category: "Metal Sculpture & Design",
    tagline: "Artists with Cerebral Palsy",
    soldCount: 19,
    shortBio:
      "David shapes clay and found objects into powerful sculptures. His tactile art invites touch and contemplation, drawing viewers into a world of form and texture.",
    fullBio:
      "David's sculptures emerge from a deep sensory engagement with materials. Each piece is a conversation between his hands and the medium, resulting in forms that feel both ancient and immediate.",
    medium: "Sculpture",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80",
    coverImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=1200&q=80",
  },
  {
    id: "lily-thompson",
    name: "Lily Thompson",
    category: "Acrylic & Large Format",
    tagline: "Artists living with Autism",
    soldCount: 41,
    shortBio:
      "Lily paints with courage and determination. Using adaptive tools she helped design herself, her vibrant acrylics are testaments to the unbreakable human spirit.",
    fullBio:
      "Using adaptive tools she helped design herself, Lily creates large-scale acrylic paintings full of movement and colour. Her work has been exhibited in galleries across the country.",
    medium: "Acrylic",
    image: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&q=80",
    coverImage: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=1200&q=80",
  },
  {
    id: "alex-martinez",
    name: "Alex Martinez",
    category: "Ink Drawing & Illustration",
    tagline: "Artists with Visual Impairment",
    soldCount: 35,
    shortBio:
      "Alex creates intricate worlds with pen and ink. His detailed drawings contain thousands of individual marks that invite meditation and wonder.",
    fullBio:
      "Alex's pen-and-ink drawings are exercises in patience and precision. Each piece contains thousands of individual marks that together build entire universes of form and texture.",
    medium: "Ink Drawing",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&q=80",
    coverImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=1200&q=80",
  },
];

export const ARTWORKS = [
  /* ── Sarah Mitchell — Watercolor ── */
  {
    id: "spring-awakening",
    artistId: "sarah-mitchell",
    category: "Watercolor",
    title: "Spring Awakening",
    price: "$450.00",
    artistReceives: "$360.00",
    description:
      "A delicate watercolor capturing the first blooms of spring. Sarah spent three weeks layering translucent washes to achieve the luminous quality of early morning light.",
    image: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800&q=80",
  },
  {
    id: "morning-dew",
    artistId: "sarah-mitchell",
    category: "Watercolor",
    title: "Morning Dew",
    price: "$380.00",
    artistReceives: "$304.00",
    description:
      "This piece captures the magical moment when morning light hits dewdrops on grass, each tiny sphere a perfect mirror of the world.",
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&q=80",
  },
  {
    id: "autumn-whispers",
    artistId: "sarah-mitchell",
    category: "Watercolor",
    title: "Autumn Whispers",
    price: "$425.00",
    artistReceives: "$340.00",
    description:
      "Rich oranges and deep reds dance across the paper in this celebration of fall. Every stroke carries the memory of crisp autumn air.",
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80",
  },
  /* ── Marcus Chen — Metal Art ── */
  {
    id: "butterfly-dreams",
    artistId: "marcus-chen",
    category: "Metal Art",
    title: "Butterfly Dreams",
    price: "$125",
    artistReceives: "$75.00",
    description:
      "Delicate metal butterflies welded into a cascading mobile. Marcus spent three weeks shaping each wing by hand.",
    image: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&q=80",
  },
  {
    id: "flower-garden",
    artistId: "marcus-chen",
    category: "Metal Art",
    title: "Flower Garden",
    price: "$145",
    artistReceives: "$87.00",
    description:
      "A blooming arrangement of hand-cut steel flowers, each petal shaped with patience and precision.",
    image: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=800&q=80",
  },
  {
    id: "abstract-spiral",
    artistId: "marcus-chen",
    category: "Metal Art",
    title: "Abstract Spiral",
    price: "$110",
    artistReceives: "$66.00",
    description:
      "A spiraling metal sculpture that captures movement frozen in time, reflecting light from every angle.",
    image: "https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800&q=80",
  },
  {
    id: "iron-postcard-i",
    artistId: "marcus-chen",
    category: "Postcard Art",
    title: "Iron Postcard I",
    price: "$45",
    artistReceives: "$27.00",
    description:
      "A miniature metal relief, small enough to mail but packed with intricate detail.",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80",
  },
  /* ── Emma Rodriguez — Mixed Media ── */
  {
    id: "joyful-chaos",
    artistId: "emma-rodriguez",
    category: "Mixed Media",
    title: "Joyful Chaos",
    price: "$520.00",
    artistReceives: "$416.00",
    description:
      "Torn paper, fabric scraps, and acrylic paint collide in a vibrant celebration of everyday beauty. Emma describes this as her happiest work.",
    image: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&q=80",
  },
  {
    id: "layered-light",
    artistId: "emma-rodriguez",
    category: "Mixed Media",
    title: "Layered Light",
    price: "$480.00",
    artistReceives: "$384.00",
    description:
      "Translucent layers of tissue paper and paint create depth and luminosity in this exploration of light passing through fragile things.",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80",
  },
  /* ── David Park — Sculpture ── */
  {
    id: "iron-bloom",
    artistId: "david-park",
    category: "Sculpture",
    title: "Iron Bloom",
    price: "$1,200.00",
    artistReceives: "$960.00",
    description:
      "Welded steel petals unfurl in this meditation on growth and resilience. David worked on this piece over six months, shaping each petal by hand.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
  },
  {
    id: "found-silence",
    artistId: "david-park",
    category: "Sculpture",
    title: "Found Silence",
    price: "$890.00",
    artistReceives: "$712.00",
    description:
      "Reclaimed wood and wire assembled into a figure of quiet contemplation. Every material carries its own history.",
    image: "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=800&q=80",
  },
  /* ── Lily Thompson — Acrylic ── */
  {
    id: "bold-horizon",
    artistId: "lily-thompson",
    category: "Acrylic",
    title: "Bold Horizon",
    price: "$560.00",
    artistReceives: "$448.00",
    description:
      "A sweeping landscape of thick impasto strokes. Lily uses adaptive grip tools to build up paint in bold, confident layers.",
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80",
  },
  {
    id: "crimson-tide",
    artistId: "lily-thompson",
    category: "Acrylic",
    title: "Crimson Tide",
    price: "$610.00",
    artistReceives: "$488.00",
    description:
      "Deep reds and burnt oranges surge across the canvas in wave-like motion, capturing the raw power of emotion in movement.",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
  },
  /* ── Alex Martinez — Ink Drawing ── */
  {
    id: "infinite-city",
    artistId: "alex-martinez",
    category: "Ink Drawing",
    title: "Infinite City",
    price: "$340.00",
    artistReceives: "$272.00",
    description:
      "Thousands of individual ink marks build a sprawling metropolis in miniature. Alex spent over 200 hours on this single piece.",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80",
  },
  {
    id: "root-system",
    artistId: "alex-martinez",
    category: "Ink Drawing",
    title: "Root System",
    price: "$295.00",
    artistReceives: "$236.00",
    description:
      "A vast network of roots and branches rendered in obsessive detail, mapping the unseen systems that sustain all living things.",
    image: "https://images.unsplash.com/photo-1580136579312-94651dfd596d?w=800&q=80",
  },
  /* ── Original Paintings — various artists ── */
  {
    id: "sunset-dreams",
    artistId: "sarah-mitchell",
    category: "Original Painting",
    title: "Sunset Dreams",
    price: "$490.00",
    artistReceives: "$392.00",
    description:
      "Warm layers of amber and gold capture a Pacific Northwest sunset. Each session painted live at dusk, light fading fast.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
  },
  {
    id: "ocean-whispers",
    artistId: "marcus-chen",
    category: "Original Painting",
    title: "Ocean Whispers",
    price: "$520.00",
    artistReceives: "$416.00",
    description:
      "Deep teal and seafoam swirl in this textured seascape, built with palette knife and a love of the Oregon coast.",
    image: "https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800&q=80",
  },
  {
    id: "joy-in-motion",
    artistId: "emma-rodriguez",
    category: "Original Painting",
    title: "Joy in Motion",
    price: "$435.00",
    artistReceives: "$348.00",
    description:
      "A burst of movement and colour — dance captured in acrylic. Emma painted this in a single exhilarating afternoon session.",
    image: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=800&q=80",
  },
  {
    id: "dance-of-colors",
    artistId: "emma-rodriguez",
    category: "Original Painting",
    title: "Dance of Colors",
    price: "$410.00",
    artistReceives: "$328.00",
    description:
      "Vivid intersecting arcs of colour celebrate the joy of movement and music. No brushes — only palette knives.",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80",
  },
  /* ── Postcard Art ── */
  {
    id: "hope-series-1",
    artistId: "lily-thompson",
    category: "Postcard Art",
    title: "Hope Series #1",
    price: "$45.00",
    artistReceives: "$27.00",
    description:
      "The first in Lily's Hope Series — a small-format oil study radiating warmth and possibility.",
    image: "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=800&q=80",
  },
  {
    id: "joy-collection",
    artistId: "lily-thompson",
    category: "Postcard Art",
    title: "Joy Collection",
    price: "$40.00",
    artistReceives: "$24.00",
    description:
      "A set of miniature works celebrating small everyday moments. Each postcard is an original, one-of-a-kind piece.",
    image: "https://images.unsplash.com/photo-1547333590-17b24b578176?w=800&q=80",
  },
  {
    id: "metal-art-series",
    artistId: "marcus-chen",
    category: "Postcard Art",
    title: "Metal Art Series",
    price: "$55.00",
    artistReceives: "$33.00",
    description:
      "Miniature metal relief cards — each one a tiny sculpture you can hold in your hand.",
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80",
  },
  {
    id: "hope-series-3",
    artistId: "emma-rodriguez",
    category: "Postcard Art",
    title: "Hope Series #3",
    price: "$45.00",
    artistReceives: "$27.00",
    description:
      "Bold washes of colour on card stock — Emma's hope series keeps growing, one small piece at a time.",
    image: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&q=80",
  },
  {
    id: "abstract-mini-2",
    artistId: "emma-rodriguez",
    category: "Postcard Art",
    title: "Abstract Mini #2",
    price: "$35.00",
    artistReceives: "$21.00",
    description:
      "Tiny but mighty — an abstract study in texture and form that rewards close inspection.",
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&q=80",
  },
];

export const EVENTS = [
  {
    id: "spring-art-exhibition-2025",
    title: "Spring Art Exhibition 2025",
    date: "March 15, 2025",
    isoDate: "2025-03-15",
    time: "10:00 AM - 6:00 PM",
    location: "Downtown Community Gallery",
    category: "Exhibition",
    attendees: "150",
    status: "Upcoming" as const,
    featured: true,
    description:
      "Join us for our biggest exhibition of the year, featuring over 100 artworks from our talented artists.",
    longDescription:
      "Experience a curated collection of stunning pieces created by our talented special-needs artists. Connect with the artists, hear their stories, and learn about their creative journey. All artworks are available for purchase, with 60% of proceeds going directly to the artists.",
    admission: "Free",
    expectedAttendees: 150,
    image: "https://images.unsplash.com/photo-1580136579312-94651dfd596d?w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1580136579312-94651dfd596d?w=200&q=80",
  },
  {
    id: "watercolor-workshop-emma",
    title: "Watercolor Workshop with Emma",
    date: "March 22, 2025",
    isoDate: "2025-03-22",
    time: "2:00 PM - 4:00 PM",
    location: "Heartful Arts Studio",
    category: "Workshop",
    attendees: "20",
    status: "Upcoming" as const,
    featured: false,
    description: "Learn watercolor techniques directly from Emma Rodriguez.",
    longDescription:
      "An intimate workshop where you'll learn Emma's signature techniques for layering colours and creating texture. All materials provided.",
    admission: "$45",
    expectedAttendees: 20,
    image: "https://images.unsplash.com/photo-1547333590-17b24b578176?w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1547333590-17b24b578176?w=200&q=80",
  },
  {
    id: "metal-art-demonstration",
    title: "Metal Art Demonstration",
    date: "April 5, 2025",
    isoDate: "2025-04-05",
    time: "1:00 PM - 3:00 PM",
    location: "Heartful Arts Studio",
    category: "Workshop",
    attendees: "30",
    status: "Upcoming" as const,
    featured: false,
    description: "Watch David Park demonstrate his sculptural process live.",
    longDescription:
      "A rare opportunity to see David at work, shaping metal and found objects into powerful sculptures.",
    admission: "Free",
    expectedAttendees: 30,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&q=80",
  },
  {
    id: "annual-art-fair-2025",
    title: "Annual Art Fair 2025",
    date: "May 10, 2025",
    isoDate: "2025-05-10",
    time: "9:00 AM - 5:00 PM",
    location: "City Center Plaza",
    category: "Art Fair",
    attendees: "500",
    status: "Upcoming" as const,
    featured: true,
    description:
      "Our biggest annual art fair, showcasing works from all our artists.",
    longDescription:
      "Browse hundreds of original artworks, meet the artists, and enjoy live demonstrations throughout the day.",
    admission: "Free",
    expectedAttendees: 500,
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=200&q=80",
  },
  {
    id: "winter-wonderland-exhibition",
    title: "Winter Wonderland Exhibition",
    date: "December 12, 2024",
    isoDate: "2024-12-12",
    time: "10:00 AM - 8:00 PM",
    location: "Downtown Community Gallery",
    category: "Exhibition",
    attendees: "200",
    status: "Past" as const,
    featured: true,
    description:
      "A winter-themed exhibition celebrating the season through art.",
    longDescription:
      "Our celebrated winter exhibition brought together seasonal works from all our artists in a magical evening showcase.",
    admission: "Free",
    expectedAttendees: 200,
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=200&q=80",
  },
  {
    id: "abstract-art-workshop-series",
    title: "Abstract Art Workshop Series",
    date: "November 15, 2024",
    isoDate: "2024-11-15",
    time: "2:00 PM - 5:00 PM",
    location: "Heartful Arts Studio",
    category: "Workshop",
    attendees: "45",
    status: "Past" as const,
    featured: false,
    description: "A series of workshops exploring abstract expression.",
    longDescription:
      "Three-session workshop series covering colour theory, composition, and expressive mark-making.",
    admission: "$120 for series",
    expectedAttendees: 45,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=200&q=80",
  },
  {
    id: "fall-festival-art-market",
    title: "Fall Festival Art Market",
    date: "October 15, 2024",
    isoDate: "2024-10-15",
    time: "9:00 AM - 6:00 PM",
    location: "City Center Plaza",
    category: "Art Fair",
    attendees: "350",
    status: "Past" as const,
    featured: false,
    description: "Annual fall art market with works from all our artists.",
    longDescription:
      "A lively outdoor market celebrating autumn with original art, crafts, and community.",
    admission: "Free",
    expectedAttendees: 350,
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=200&q=80",
  },
];

export const ORDERS = [
  {
    id: "ORD-2024-001",
    customer: "Sarah Johnson",
    email: "sarah.j@email.com",
    items: 2,
    total: "$830.00",
    status: "new" as const,
    date: "2024-11-13 14:30",
    shippingAddress: "123 Main St, San Francisco, CA 94105",
    paymentMethod: "Credit Card",
    lineItems: [
      { title: "Sunset Dreams", artist: "Emma Chen", quantity: 1, price: "$450.00" },
      { title: "Urban Reflection", artist: "Marcus Thompson", quantity: 1, price: "$380.00" },
    ],
  },
  {
    id: "ORD-2024-002",
    customer: "Michael Brown",
    email: "m.brown@email.com",
    items: 1,
    total: "$560.00",
    status: "processing" as const,
    date: "2024-11-12 09:15",
    shippingAddress: "456 Oak Ave, Portland, OR 97201",
    paymentMethod: "PayPal",
    lineItems: [
      { title: "Ocean Dreaming", artist: "Lily Thompson", quantity: 1, price: "$560.00" },
    ],
  },
  {
    id: "ORD-2024-003",
    customer: "Emily Davis",
    email: "emily.d@email.com",
    items: 1,
    total: "$520.00",
    status: "shipped" as const,
    date: "2024-11-10 16:45",
    shippingAddress: "789 Pine St, Seattle, WA 98101",
    paymentMethod: "Credit Card",
    lineItems: [
      { title: "Energy in Motion", artist: "Marcus Chen", quantity: 1, price: "$520.00" },
    ],
  },
  {
    id: "ORD-2024-004",
    customer: "David Wilson",
    email: "d.wilson@email.com",
    items: 1,
    total: "$340.00",
    status: "delivered" as const,
    date: "2024-11-08 11:20",
    shippingAddress: "321 Elm Rd, Austin, TX 78701",
    paymentMethod: "Credit Card",
    lineItems: [
      { title: "Morning Silence", artist: "Alex Martinez", quantity: 1, price: "$340.00" },
    ],
  },
];

export const ATTENDEES = [
  {
    id: "1",
    name: "Sarah Johnson",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    email: "sarah.j@email.com",
    phone: "+1 (555) 123-4567",
    registeredAt: "Dec 20, 2024, 10:00 AM",
    attendeeCount: 2,
    dietaryRestrictions: "Vegetarian",
    specialRequirements: null as string | null,
  },
  {
    id: "2",
    name: "Michael Chen",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    email: "m.chen@example.com",
    phone: "+1 (555) 234-5678",
    registeredAt: "Dec 18, 2024, 02:30 PM",
    attendeeCount: 1,
    dietaryRestrictions: null as string | null,
    specialRequirements: null as string | null,
  },
  {
    id: "3",
    name: "Emma Rodriguez",
    avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    email: "emma.r@gmail.com",
    phone: "+1 (555) 345-6789",
    registeredAt: "Dec 15, 2024, 09:15 AM",
    attendeeCount: 3,
    dietaryRestrictions: "Gluten-free",
    specialRequirements: "Wheelchair accessible seating",
  },
  {
    id: "4",
    name: "David Thompson",
    avatar: "https://randomuser.me/api/portraits/men/71.jpg",
    email: "d.thompson@outlook.com",
    phone: "+1 (555) 456-7890",
    registeredAt: "Dec 22, 2024, 04:45 PM",
    attendeeCount: 1,
    dietaryRestrictions: null as string | null,
    specialRequirements: null as string | null,
  },
];
